### ISSUE TITLE
Add `titleColor` option to notiflix confirm

### ISSUE THREAD

**Issue by tomicapretto** [dreamRs/shinypop#1]
Hi! Thank you for this great package, my apps now look much better!

I would like to know if it is possible to add the `titleColor` argument to `shinypop::use_notiflix_confirm()` so one can use the 
same color for the title and the confirm button background, for example.

If you want, I can try to incorporate this and then make a PR to incorporate the changes.

Thank you!

**Comment by pvictor** [comment]
You're welcome :) 

Yes that's doable, I think this will require to upgrade Notiflix JS library (https://github.com/notiflix/Notiflix).
If you want to make a PR it'll be great and you might be quicker than me to integrate it.

Victor

**Comment by tomicapretto** [comment]
Thanks for the quick response. I've just created the PR :)

**Comment by tomicapretto** [comment]
Closing since PR #2 is merged
